### ISSUE TITLE
Beginner Issues in test.py working w/ Google Colab (Tensorflow 1.14)

### ISSUE THREAD

**Issue by SvSz** [konstantg/dem-fill#8]
Trying to run 

```python
# Norway Landscape
python test.py --image data/land01.tif --mask data/land01mask.png --output data/land01out.tif --checkpoint_dir model_logs/norway_land/
```

Using Google Colab, I tried installing different versions from Tensorflow, unfortunatly 1.7 is not avaiable here.
I used the oldest release possible:

```python
!pip install tensorflow==1.14
```

I adapted the directory line form above to my folder organisation, the following Error Code is the result:

```python
[...]
[2021-05-06 11:48:45 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[2021-05-06 11:48:45 @__init__.py:80] Saving logging to file: neuralgym_logs/20210506114845452698.
[2021-05-06 11:48:45 @utils.py:157] NumExpr defaulting to 2 threads.
# gpu        pid  type    sm   mem   enc   dec   command
# Idx          #   C/G     %     %     %     %   name
    0          -     -     -     -     -     -   -              

[2021-05-06 11:48:46 @gpus.py:20] Set env: CUDA_VISIBLE_DEVICES=[0].
Traceback (most recent call last):
  File "/content/drive/MyDrive/ML_Thesis/06_CNN-Architectures/Gavriil_Muntingh_dem-fill-master/test.py", line 30, in <module>
    im_min = image.min()
AttributeError: 'NoneType' object has no attribute 'min'
```

Accordingly, the Following Line 30 in test.py does not work:

```python
22 if __name__ == "__main__":
23    ng.get_gpus(1)
24    args = parser.parse_args()
25
26    model = InpaintCAModel()
27
28    image = cv2.imread(args.image, -1)
29   inim = cv2.imread(args.image, -1)
30    im_min = image.min()
31    im_max = image.max()
```

changing the code I fixed the problem here by:

```python
30    im_min = np.min(image)
31    im_max = np.max(image)
```

Another Error appears further downwards:

```python
[2021-05-06 11:52:17 @__init__.py:79] Set root logger. Unset logger with neuralgym.unset_logger().
[2021-05-06 11:52:17 @__init__.py:80] Saving logging to file: neuralgym_logs/20210506115217106061.
[2021-05-06 11:52:17 @utils.py:157] NumExpr defaulting to 2 threads.
# gpu        pid  type    sm   mem   enc   dec   command
# Idx          #   C/G     %     %     %     %   name
    0          -     -     -     -     -     -   -              

[2021-05-06 11:52:17 @gpus.py:20] Set env: CUDA_VISIBLE_DEVICES=[0].
Traceback (most recent call last):
  File "/content/drive/MyDrive/ML_Thesis/06_CNN-Architectures/Gavriil_Muntingh_dem-fill-master/test.py", line 37, in <module>
    if len(image.shape) < 3:
AttributeError: 'NoneType' object has no attribute 'shape'
```

When I understand this correctly, attribute image is loaded by

```python
--image data/land01.tif
```

## Why does this image not have a shape and how can I change this? Are these issues related to the higher Tensorflow Versions?

**Comment by SvSz** [comment]
https://github.com/JiahuiYu/generative_inpainting/issues/47#issuecomment-425733968
