### ISSUE TITLE
Assertion error loss is nan

### ISSUE THREAD

**Issue by Dsmagleby** [konstantg/dem-fill#9]
I am trying to train on a collection of .tif DEM files, but I am getting the below error, I have made sure that data_from_fnames.py correctly loads the files and that they do not contain any nan values. I have also tried with different dtypes float32, float64 etc. Could it be that I am missing something blindingly obvious? 

`Traceback (most recent call last):
  File "train.py", line 112, in <module>
    trainer.train()
  File "C:\Users\dsmag\anaconda3\envs\demfill\lib\site-packages\neuralgym\train\trainer.py", line 136, in train
    cb.run(sess, step)
  File "C:\Users\dsmag\anaconda3\envs\demfill\lib\site-packages\neuralgym\callbacks\secondary_trainer.py", line 26, in run
    self.train()
  File "C:\Users\dsmag\anaconda3\envs\demfill\lib\site-packages\neuralgym\train\trainer.py", line 146, in train
    assert not np.isnan(loss_value)
AssertionError`

**Comment by Dsmagleby** [comment]
A brief update on this issue, the cause was indeed obvious, setting the batch size too high was the cause. The implementation does not throw an error when the GPU is OOM instead it seemingly incompletely loads the images which cause the nan value from the loss function.
